package rms;

import java.awt.Color;
import javax.swing.JFrame;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author hm
 */
public class AllTenant extends javax.swing.JFrame {

    DefaultTableModel model;

    /**
     * Creates new form AllTenant
     */
    public AllTenant() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        getAllTenant();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSearchTenant = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtstartdate = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtPhoneno = new javax.swing.JTextField();
        txtroomno = new javax.swing.JTextField();
        txtmonthlyrent = new javax.swing.JTextField();
        comboxStatus = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        panelSideBar = new javax.swing.JPanel();
        panelSearchRecord = new javax.swing.JPanel();
        btnAllTenant = new javax.swing.JLabel();
        panelHome = new javax.swing.JPanel();
        btnHome = new javax.swing.JLabel();
        panelEditc = new javax.swing.JPanel();
        btnEditTenant = new javax.swing.JLabel();
        panelCourseL = new javax.swing.JPanel();
        btnMonthlyRecords = new javax.swing.JLabel();
        panelBack = new javax.swing.JPanel();
        btnMonthlyRent = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(245, 232, 221));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SimSun-ExtB", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Rent Management System");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 280, 60));

        jLabel9.setFont(new java.awt.Font("SimSun-ExtB", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("All Tenant");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 160, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 1090, 100));

        jPanel1.setBackground(new java.awt.Color(204, 211, 202));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setOpaque(false);

        tblSearchTenant.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S.No", "Name", "Phone No", "Room  No", "Monthly Rent", "Start date", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSearchTenant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSearchTenantMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSearchTenant);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 680, 490));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Status :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 80, 30));

        txtstartdate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtstartdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstartdateActionPerformed(evt);
            }
        });
        jPanel1.add(txtstartdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 200, 38));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("S.No :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 80, 30));

        txtid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        jPanel1.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 200, 38));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Name :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 80, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Phone No :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 80, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Room No :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 80, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Monthly Rent :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 100, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Start Date :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 80, 30));

        txtname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        jPanel1.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 200, 38));

        txtPhoneno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPhoneno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhonenoActionPerformed(evt);
            }
        });
        jPanel1.add(txtPhoneno, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 200, 38));

        txtroomno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtroomno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtroomnoActionPerformed(evt);
            }
        });
        jPanel1.add(txtroomno, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 200, 38));

        txtmonthlyrent.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtmonthlyrent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmonthlyrentActionPerformed(evt);
            }
        });
        jPanel1.add(txtmonthlyrent, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 200, 38));

        comboxStatus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        comboxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Available", "Unavailable" }));
        comboxStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxStatusActionPerformed(evt);
            }
        });
        jPanel1.add(comboxStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 200, 38));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, 100, 40));

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 100, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 1090, 600));

        panelSideBar.setBackground(new java.awt.Color(238, 211, 217));
        panelSideBar.setPreferredSize(new java.awt.Dimension(370, 740));
        panelSideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelSearchRecord.setBackground(new java.awt.Color(218, 163, 175));
        panelSearchRecord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelSearchRecord.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        panelSearchRecord.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAllTenant.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        btnAllTenant.setForeground(new java.awt.Color(255, 255, 255));
        btnAllTenant.setText("All Tenant");
        btnAllTenant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAllTenantMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAllTenantMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAllTenantMouseExited(evt);
            }
        });
        panelSearchRecord.add(btnAllTenant, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 50));

        panelSideBar.add(panelSearchRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 210, 70));

        panelHome.setBackground(new java.awt.Color(218, 163, 175));
        panelHome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelHome.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        panelHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHome.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setText("Home");
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHomeMouseExited(evt);
            }
        });
        panelHome.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 50));

        panelSideBar.add(panelHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 210, 70));

        panelEditc.setBackground(new java.awt.Color(218, 163, 175));
        panelEditc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelEditc.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        panelEditc.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEditTenant.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        btnEditTenant.setForeground(new java.awt.Color(255, 255, 255));
        btnEditTenant.setText("Add Tenant");
        btnEditTenant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditTenantMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditTenantMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditTenantMouseExited(evt);
            }
        });
        panelEditc.add(btnEditTenant, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 50));

        panelSideBar.add(panelEditc, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 210, 70));

        panelCourseL.setBackground(new java.awt.Color(218, 163, 175));
        panelCourseL.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelCourseL.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        panelCourseL.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMonthlyRecords.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        btnMonthlyRecords.setForeground(new java.awt.Color(255, 255, 255));
        btnMonthlyRecords.setText("Back");
        btnMonthlyRecords.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMonthlyRecordsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMonthlyRecordsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMonthlyRecordsMouseExited(evt);
            }
        });
        panelCourseL.add(btnMonthlyRecords, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 50));

        panelSideBar.add(panelCourseL, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 210, 70));

        panelBack.setBackground(new java.awt.Color(218, 163, 175));
        panelBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelBack.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        panelBack.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMonthlyRent.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        btnMonthlyRent.setForeground(new java.awt.Color(255, 255, 255));
        btnMonthlyRent.setText(" Monthly Rent");
        btnMonthlyRent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMonthlyRentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMonthlyRentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMonthlyRentMouseExited(evt);
            }
        });
        panelBack.add(btnMonthlyRent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 200, 50));

        panelSideBar.add(panelBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 210, 70));

        getContentPane().add(panelSideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void clearTable() {
        DefaultTableModel model = (DefaultTableModel) tblSearchTenant.getModel();
        model.setRowCount(0);
    }

    public void getAllTenant() {
        try {
            Connection con = DbConnection.getConnection();
            PreparedStatement pst = con.prepareStatement("Select * from tenant");
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                int id = rs.getInt("id");
                String name = rs.getString("name");
                String phoneNo = rs.getString("phone_no");
                String roomNo = rs.getString("room_no");
                double monthlyRent = rs.getDouble("monthly_rent");
                String startDate = rs.getString("start_date");
                String status = rs.getString("status");

                Object[] obj = {id, name, phoneNo, roomNo, monthlyRent, startDate, status};
                model = (DefaultTableModel) tblSearchTenant.getModel();
                model.addRow(obj);

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void update(int id, String name, String phoneNO, String roomNo, double monthlyRent, String startDate, String status) {
        try {
            Connection con = DbConnection.getConnection();
            PreparedStatement pst = con.prepareStatement("update tenant set name = ?, phone_no = ?,"
                    + "room_no=?,monthly_rent=?,start_date=?,status=? where id = ?");
            pst.setString(1, name);
            pst.setString(2, phoneNO);
            pst.setString(3, roomNo);
            pst.setDouble(4, monthlyRent);
            pst.setString(5, startDate);
            pst.setString(6, status);
            pst.setInt(7, id);
            int rowCount = pst.executeUpdate();
            if (rowCount == 1) {
                JOptionPane.showMessageDialog(this, "Tenant update sussccefully.");
                clearTable();
                getAllTenant();
            } else {
                JOptionPane.showMessageDialog(this, "Tenant updation failed.");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void delete(int id) {
        try {
            Connection con = DbConnection.getConnection();
            PreparedStatement pst = con.prepareStatement("update tenant set status='Unavailable' where id = ?");

            pst.setInt(1, id);
            int rowcount = pst.executeUpdate();
            if (rowcount == 1) {
                JOptionPane.showMessageDialog(this, "Tenant Delete succesfully.");
                clearTable();
                getAllTenant();
            } else {
                JOptionPane.showMessageDialog(this, "Tenant deletion failed.");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Tenant deletion failed.");
            e.printStackTrace();
        }
    }

    private void btnAllTenantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAllTenantMouseClicked
        AllTenant allTenant = new AllTenant();
        allTenant.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAllTenantMouseClicked

    private void btnAllTenantMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAllTenantMouseEntered
        Color color = new Color(218, 147, 163);
        panelSearchRecord.setBackground(color);
    }//GEN-LAST:event_btnAllTenantMouseEntered

    private void btnAllTenantMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAllTenantMouseExited
        Color color = new Color(218, 163, 175);
        panelSearchRecord.setBackground(color);
    }//GEN-LAST:event_btnAllTenantMouseExited

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        Home h = new Home();
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseEntered
        Color color = new Color(218, 147, 163);
        panelHome.setBackground(color);
    }//GEN-LAST:event_btnHomeMouseEntered

    private void btnHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseExited
        Color color = new Color(218, 163, 175);
        panelHome.setBackground(color);
    }//GEN-LAST:event_btnHomeMouseExited

    private void btnEditTenantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditTenantMouseClicked
        Tenant tenant = new Tenant();

        tenant.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEditTenantMouseClicked

    private void btnEditTenantMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditTenantMouseEntered
        Color color = new Color(218, 147, 163);
        panelEditc.setBackground(color);
    }//GEN-LAST:event_btnEditTenantMouseEntered

    private void btnEditTenantMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditTenantMouseExited
        Color color = new Color(218, 163, 175);
        panelEditc.setBackground(color);
    }//GEN-LAST:event_btnEditTenantMouseExited

    private void btnMonthlyRecordsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMonthlyRecordsMouseClicked
        Home home = new Home();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMonthlyRecordsMouseClicked

    private void btnMonthlyRecordsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMonthlyRecordsMouseEntered
        Color color = new Color(218, 147, 163);
        panelCourseL.setBackground(color);
    }//GEN-LAST:event_btnMonthlyRecordsMouseEntered

    private void btnMonthlyRecordsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMonthlyRecordsMouseExited
        Color color = new Color(218, 163, 175);
        panelCourseL.setBackground(color);
    }//GEN-LAST:event_btnMonthlyRecordsMouseExited

    private void btnMonthlyRentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMonthlyRentMouseClicked
        MonthlyDetails details = new MonthlyDetails();
        details.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMonthlyRentMouseClicked

    private void btnMonthlyRentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMonthlyRentMouseEntered
        Color color = new Color(218, 147, 163);
        panelBack.setBackground(color);
    }//GEN-LAST:event_btnMonthlyRentMouseEntered

    private void btnMonthlyRentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMonthlyRentMouseExited
        Color color = new Color(218, 163, 175);
        panelBack.setBackground(color);
    }//GEN-LAST:event_btnMonthlyRentMouseExited

    private void txtstartdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstartdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstartdateActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtPhonenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhonenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhonenoActionPerformed

    private void txtroomnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtroomnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtroomnoActionPerformed

    private void txtmonthlyrentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmonthlyrentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmonthlyrentActionPerformed

    private void comboxStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboxStatusActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int id = Integer.parseInt(txtid.getText());
        delete(id);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        int id = Integer.parseInt(txtid.getText());
        String name = txtname.getText();
        String phoneNo = txtPhoneno.getText();
        String roomNo = txtroomno.getText();
        double monthlyRent = Double.parseDouble(txtmonthlyrent.getText());
        String startDate = txtstartdate.getText();
        String status = comboxStatus.getSelectedItem().toString();

        update(id, name, phoneNo, roomNo, monthlyRent, startDate, status);


    }//GEN-LAST:event_jButton2ActionPerformed

    private void tblSearchTenantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSearchTenantMouseClicked
        int rowno = tblSearchTenant.getSelectedRow();
        TableModel modle = tblSearchTenant.getModel();
        txtid.setText(model.getValueAt(rowno, 0).toString());
        txtname.setText((String) model.getValueAt(rowno, 1));
        txtPhoneno.setText(modle.getValueAt(rowno, 2).toString());
        txtroomno.setText(model.getValueAt(rowno, 3).toString());
        txtmonthlyrent.setText(model.getValueAt(rowno, 4).toString());
        txtstartdate.setText(model.getValueAt(rowno, 5).toString());
        comboxStatus.setSelectedItem(model.getValueAt(rowno, 6));

    }//GEN-LAST:event_tblSearchTenantMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AllTenant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AllTenant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AllTenant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AllTenant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AllTenant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAllTenant;
    private javax.swing.JLabel btnEditTenant;
    private javax.swing.JLabel btnHome;
    private javax.swing.JLabel btnMonthlyRecords;
    private javax.swing.JLabel btnMonthlyRent;
    private javax.swing.JComboBox<String> comboxStatus;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelBack;
    private javax.swing.JPanel panelCourseL;
    private javax.swing.JPanel panelEditc;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelSearchRecord;
    private javax.swing.JPanel panelSideBar;
    private javax.swing.JTable tblSearchTenant;
    private javax.swing.JTextField txtPhoneno;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtmonthlyrent;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtroomno;
    private javax.swing.JTextField txtstartdate;
    // End of variables declaration//GEN-END:variables
}
