/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rms;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author hm
 */
public class Tenant extends javax.swing.JFrame {

    /**
     * Creates new form Tenant
     */
    public Tenant() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        int receiptNo = getReceiptNo();
        txt_id.setText(Integer.toString(receiptNo));
    }

    public boolean validation() {
        String phoneNo = txt_phoneNo.getText();
        if (txt_Name.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter name.");
            return false;
        }
        if (phoneNo.equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter phone number.");
        }
        if (txt_monthlyRent.getText().equals("") || txt_monthlyRent.getText().matches("[0-9]+") == false) {
            JOptionPane.showMessageDialog(this, "Please enter amount(in numbers).");
            return false;
        }
        return true;
    }

    public int getReceiptNo() {
        int receiptNo = 0;
        try {
            Connection con = DbConnection.getConnection();
            PreparedStatement pst = con.prepareStatement("Select max(id) from tenant");
            ResultSet rs = pst.executeQuery();
            if (rs.next() == true) {
                receiptNo = rs.getInt(1);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return receiptNo + 1;
    }

    public String dataInsert() {

        String status = "";
        int receiptNo = Integer.parseInt(txt_id.getText());
        String name = txt_Name.getText();
        String phoneNo = txt_phoneNo.getText();
        String roomNo = txt_roomNo.getText();
        double monthlyRent = Double.parseDouble(txt_monthlyRent.getText());
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String date = dateFormat.format(startDate.getDate());
        String statusAvailableUnavailable = comboxStatus.getSelectedItem().toString();

        try {
            Connection con = DbConnection.getConnection();
            PreparedStatement pst = con.prepareStatement("Insert into tenant values (?,?,?,?,?,?,?)");
            pst.setInt(1, receiptNo);
            pst.setString(2, name);
            pst.setString(3, phoneNo);
            pst.setString(4, roomNo);
            pst.setDouble(5, monthlyRent);
            pst.setString(6, date);
            pst.setString(7, statusAvailableUnavailable);

            int rowCount = pst.executeUpdate();
            if (rowCount == 1) {
                status = "success";
            } else {
                status = "failed";
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

        return status;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_Name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_phoneNo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_monthlyRent = new javax.swing.JTextField();
        startDate = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        txt_roomNo = new javax.swing.JTextField();
        btn_submit = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        comboxStatus = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        panelSideBar = new javax.swing.JPanel();
        panelSearchRecord = new javax.swing.JPanel();
        btnAllTenant = new javax.swing.JLabel();
        panelHome = new javax.swing.JPanel();
        btnHome = new javax.swing.JLabel();
        panelEditc = new javax.swing.JPanel();
        btnEditTenant = new javax.swing.JLabel();
        panelCourseL = new javax.swing.JPanel();
        btnMonthlyRecords = new javax.swing.JLabel();
        panelBack = new javax.swing.JPanel();
        btnMonthlyRent = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 211, 202));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Receipt no :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 130, 30));

        txt_id.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });
        jPanel1.add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 42, 170, 38));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Start Date :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 30, 130, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Status :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 110, 130, 30));

        txt_Name.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NameActionPerformed(evt);
            }
        });
        jPanel1.add(txt_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 290, 38));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Phone Number :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 130, 30));

        txt_phoneNo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_phoneNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_phoneNoActionPerformed(evt);
            }
        });
        jPanel1.add(txt_phoneNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 290, 38));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Monthly Rent :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 130, 30));

        txt_monthlyRent.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_monthlyRent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_monthlyRentActionPerformed(evt);
            }
        });
        jPanel1.add(txt_monthlyRent, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 290, 38));
        jPanel1.add(startDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 30, 170, 38));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Room No :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 130, 30));

        txt_roomNo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_roomNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_roomNoActionPerformed(evt);
            }
        });
        jPanel1.add(txt_roomNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 290, 38));

        btn_submit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_submit.setText("Submit");
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });
        jPanel1.add(btn_submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, 140, 38));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Name :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 130, 30));

        comboxStatus.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        comboxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Available", "Unavailable" }));
        comboxStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxStatusActionPerformed(evt);
            }
        });
        jPanel1.add(comboxStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 100, 170, 38));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 98, 1080, 600));

        jPanel2.setBackground(new java.awt.Color(245, 232, 221));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SimSun-ExtB", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Rent Management System");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 280, 60));

        jLabel9.setFont(new java.awt.Font("SimSun-ExtB", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Add Tenant");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 160, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 0, 1080, 100));

        panelSideBar.setBackground(new java.awt.Color(238, 211, 217));
        panelSideBar.setPreferredSize(new java.awt.Dimension(370, 740));
        panelSideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelSearchRecord.setBackground(new java.awt.Color(218, 163, 175));
        panelSearchRecord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelSearchRecord.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        panelSearchRecord.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAllTenant.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        btnAllTenant.setForeground(new java.awt.Color(255, 255, 255));
        btnAllTenant.setText("All Tenant");
        btnAllTenant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAllTenantMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAllTenantMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAllTenantMouseExited(evt);
            }
        });
        panelSearchRecord.add(btnAllTenant, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 50));

        panelSideBar.add(panelSearchRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 210, 70));

        panelHome.setBackground(new java.awt.Color(218, 163, 175));
        panelHome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelHome.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        panelHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHome.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setText("Home");
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHomeMouseExited(evt);
            }
        });
        panelHome.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 50));

        panelSideBar.add(panelHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 210, 70));

        panelEditc.setBackground(new java.awt.Color(218, 163, 175));
        panelEditc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelEditc.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        panelEditc.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEditTenant.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        btnEditTenant.setForeground(new java.awt.Color(255, 255, 255));
        btnEditTenant.setText("Add Tenant");
        btnEditTenant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditTenantMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditTenantMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditTenantMouseExited(evt);
            }
        });
        panelEditc.add(btnEditTenant, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 50));

        panelSideBar.add(panelEditc, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 210, 70));

        panelCourseL.setBackground(new java.awt.Color(218, 163, 175));
        panelCourseL.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelCourseL.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        panelCourseL.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMonthlyRecords.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        btnMonthlyRecords.setForeground(new java.awt.Color(255, 255, 255));
        btnMonthlyRecords.setText("Back ");
        btnMonthlyRecords.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMonthlyRecordsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMonthlyRecordsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMonthlyRecordsMouseExited(evt);
            }
        });
        panelCourseL.add(btnMonthlyRecords, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 50));

        panelSideBar.add(panelCourseL, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 210, 70));

        panelBack.setBackground(new java.awt.Color(218, 163, 175));
        panelBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelBack.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        panelBack.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMonthlyRent.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        btnMonthlyRent.setForeground(new java.awt.Color(255, 255, 255));
        btnMonthlyRent.setText(" Monthly Rent");
        btnMonthlyRent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMonthlyRentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMonthlyRentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMonthlyRentMouseExited(evt);
            }
        });
        panelBack.add(btnMonthlyRent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 200, 50));

        panelSideBar.add(panelBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 210, 70));

        getContentPane().add(panelSideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 700));

        setSize(new java.awt.Dimension(1382, 710));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void txt_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NameActionPerformed

    private void txt_phoneNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_phoneNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_phoneNoActionPerformed

    private void txt_monthlyRentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_monthlyRentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_monthlyRentActionPerformed

    private void txt_roomNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_roomNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_roomNoActionPerformed

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed

        if (validation() == true) {
            String result = dataInsert();
            if (result.equals("success")) {
                JOptionPane.showMessageDialog(this, "Data insert successfuly.");

            } else {
                JOptionPane.showMessageDialog(this, "Record insertion failed.");
            }
        }

    }//GEN-LAST:event_btn_submitActionPerformed

    private void comboxStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboxStatusActionPerformed

    private void btnAllTenantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAllTenantMouseClicked
        AllTenant allTenant = new AllTenant();
        allTenant.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAllTenantMouseClicked

    private void btnAllTenantMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAllTenantMouseEntered
        Color color = new Color(218, 147, 163);
        panelSearchRecord.setBackground(color);
    }//GEN-LAST:event_btnAllTenantMouseEntered

    private void btnAllTenantMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAllTenantMouseExited
        Color color = new Color(218, 163, 175);
        panelSearchRecord.setBackground(color);
    }//GEN-LAST:event_btnAllTenantMouseExited

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        Home h = new Home();
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseEntered
        Color color = new Color(218, 147, 163);
        panelHome.setBackground(color);
    }//GEN-LAST:event_btnHomeMouseEntered

    private void btnHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseExited
        Color color = new Color(218, 163, 175);
        panelHome.setBackground(color);
    }//GEN-LAST:event_btnHomeMouseExited

    private void btnEditTenantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditTenantMouseClicked
        Tenant tenant = new Tenant();

        tenant.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEditTenantMouseClicked

    private void btnEditTenantMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditTenantMouseEntered
        Color color = new Color(218, 147, 163);
        panelEditc.setBackground(color);
    }//GEN-LAST:event_btnEditTenantMouseEntered

    private void btnEditTenantMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditTenantMouseExited
        Color color = new Color(218, 163, 175);
        panelEditc.setBackground(color);
    }//GEN-LAST:event_btnEditTenantMouseExited

    private void btnMonthlyRecordsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMonthlyRecordsMouseClicked
        Home home = new Home();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMonthlyRecordsMouseClicked

    private void btnMonthlyRecordsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMonthlyRecordsMouseEntered
        Color color = new Color(218, 147, 163);
        panelCourseL.setBackground(color);
    }//GEN-LAST:event_btnMonthlyRecordsMouseEntered

    private void btnMonthlyRecordsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMonthlyRecordsMouseExited
        Color color = new Color(218, 163, 175);
        panelCourseL.setBackground(color);
    }//GEN-LAST:event_btnMonthlyRecordsMouseExited

    private void btnMonthlyRentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMonthlyRentMouseClicked
        MonthlyDetails details = new MonthlyDetails();
        details.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMonthlyRentMouseClicked

    private void btnMonthlyRentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMonthlyRentMouseEntered
        Color color = new Color(218, 147, 163);
        panelBack.setBackground(color);
    }//GEN-LAST:event_btnMonthlyRentMouseEntered

    private void btnMonthlyRentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMonthlyRentMouseExited
        Color color = new Color(218, 163, 175);
        panelBack.setBackground(color);
    }//GEN-LAST:event_btnMonthlyRentMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tenant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tenant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tenant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tenant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tenant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAllTenant;
    private javax.swing.JLabel btnEditTenant;
    private javax.swing.JLabel btnHome;
    private javax.swing.JLabel btnMonthlyRecords;
    private javax.swing.JLabel btnMonthlyRent;
    private javax.swing.JButton btn_submit;
    private javax.swing.JComboBox<String> comboxStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelBack;
    private javax.swing.JPanel panelCourseL;
    private javax.swing.JPanel panelEditc;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelSearchRecord;
    private javax.swing.JPanel panelSideBar;
    private com.toedter.calendar.JDateChooser startDate;
    private javax.swing.JTextField txt_Name;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_monthlyRent;
    private javax.swing.JTextField txt_phoneNo;
    private javax.swing.JTextField txt_roomNo;
    // End of variables declaration//GEN-END:variables
}
